name: test
on:   push
#   pull_request:
#     types:
#       - opened
jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      
      - name: Super-Linter
        uses: github/super-linter@v4.9.5